version: 2.1

commands:
  setup:
    steps:
      - run:
          name: 'CI Setup'
          command: |
            ./dev ci-setup
  collect-test-output:
    steps:
      - run:
          name: 'Collect test artifacts'
          when: always
          command: |
            ./dev collect-test-results ~/junit
      - store_test_results:
          path: ~/junit

jobs:
  x64-test:
    docker:
      - image: fedora:38
    steps:
      - checkout
      - setup
      - run:
          name: 'Run tests'
          command: >-
            bazel test
            --config=dbg
            --test_output=errors
            //...
      - collect-test-output
  arm64-test:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - setup
      - run:
          name: 'Run tests'
          # We don't run with ubsan mode because of clang linking bugs:
          # See: https://github.com/envoyproxy/envoy/issues/13973
          command: >-
            bazel test
            --config=asan
            --test_output=errors
            //...
      - collect-test-output


workflows:
  wasmcc:
    jobs:
      - x64-test
      - arm64-test
