version: 2.1

commands:
  setup:
    steps:
      - run:
          name: 'CI Setup'
          command: |
            ./dev ci-setup
  bazel-test:
    steps:
      - run:
          name: 'Run tests'
          command: |
            bazel test --config=ci //...

jobs:
  x64-test:
    docker:
      - image: fedora:38
    steps:
      - checkout
      - setup
      - bazel-test
  arm64-test:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - setup
      - bazel-test

workflows:
  wasmcc:
    jobs:
      - x64-test
      - arm64-test
