version: 2.1

commands:
  install-deps:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run:
          name: 'Install dep packages'
          command: |
            fedora_deps=(
              clang
              curl
              git
              llvm
              lld
              pkg-config
            )
            dnf install -y "${fedora_deps[@]}"
  install-bazelisk:
    parameters:
      arch:
        default: ""
        type: string
    steps:
      - run:
          name: 'Setup bazelisk'
          command: |
            curl -SL -o /tmp/bazel \
              https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-<<parameters.arch>>
            sudo mv /tmp/bazel /usr/local/bin/bazel
            sudo chmod +x /usr/local/bin/bazel
  bazel-test:
    steps:
      - run:
          name: 'Run tests'
          command: |
            clang --version
            bazel test --config=ci //...

jobs:
  x64-test:
    resource_class: large
    docker:
      - image: fedora:38
    steps:
      - install-deps
      - checkout
      - install-bazelisk:
          arch: "amd64"
      - bazel-test
  arm64-test:
    resource_class: arm.large
    docker:
      - image: fedora:38
    steps:
      - install-deps
      - checkout
      - install-bazelisk:
          arch: "amd64"
      - bazel-test

workflows:
  wasmcc:
    jobs:
      - x64-test
      - arm64-test
