version: 2.1

jobs:
  x64-test:
    docker:
      - image: fedora:38
    steps:
      - run:
          name: 'Install dep packages'
          command: |
            fedora_deps=(
              clang
              curl
              git
              llvm
              lld
              pkg-config
            )
            dnf install -y "${fedora_deps[@]}"
      - checkout
      - run:
          name: 'Setup bazelisk'
          command: |
            curl -SL -o /tmp/bazel \
              https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-amd64
            sudo mv /tmp/bazel /usr/local/bin/bazel
            sudo chmod +x /usr/local/bin/bazel
      - run:
          name: "Run tests"
          command: |
            clang --version
            bazel test --config=ci //...

workflows:
  wasmcc:
    jobs:
      - x64-test
