version: 2.1

commands:
  collect-test-output:
    steps:
      - run:
          name: 'Collect test artifacts'
          when: always
          command: |
            ./dev collect-test-results ~/junit
      - store_test_results:
          path: ~/junit

jobs:
  x64-test:
    docker:
      - image: rockwotj/wasmcc-ci:pr16
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Run tests'
          command: >-
            bazel test
            --config=dbg
            --test_output=errors
            //...
      - collect-test-output
  arm64-test:
    docker:
      - image: rockwotj/wasmcc-ci:pr16
    resource_class: arm.large
    steps:
      - checkout
      - run:
          name: 'Run tests'
          command: >-
            bazel test
            --config=dbg
            --test_output=errors
            //...
      - collect-test-output


workflows:
  wasmcc:
    jobs:
      - x64-test
      - arm64-test
