package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "wat",
    srcs = ["wat.cc"],
    hdrs = ["wat.h"],
    deps = [
        "//base:bytes",
        "//third_party/wabt",
    ],
)
