cc_library(
    name = "x64",
    srcs = [
        "register_tracker.cc",
        "runtime_stack.cc",
    ],
    hdrs = [
        "register_tracker.h",
        "runtime_stack.h",
    ],
    deps = [
        "//core:value",
        "//third_party/absl/container:fixed_array",
        "//third_party/asmjit",
    ],
)
