cc_library(
    name = "common",
    srcs = [
        "exception.cc",
        "util.cc",
    ],
    hdrs = [
        "exception.h",
        "util.h",
    ],
    deps = [
        "//third_party/asmjit",
    ],
)
